### ISSUE TITLE
Probar Named Entity Recognition (NER) en el corpus de telediarios

### ISSUE THREAD

**Issue by dcabo** [civio/verba#10]
I started testing entity extraction with [TextRazor](https://www.textrazor.com/demo), just so I didn't have to install anything, but we should explore other alternatives.

TextRazor seems to do a good work getting entities, and it seems like a valuable addition to segmentation (#7). It looks better if we clean the txt file a bit, i.e. join the fragmented sentences. This is something we may have to do anyway, for clarity: join all sentences in a block. But the results seem to be the same.

**Comment by rafaharo** [comment]
Menuda currada de comparación macho. Mis dieses
