### ISSUE TITLE
Usar frases como unidad de búsqueda / análisis

### ISSUE THREAD

**Issue by dcabo** [civio/verba#16]
Hasta ahora estamos usando los fragmentos de los ficheros de entrada, `.vtt`. O sea, el texto de las 1-2 líneas que aparecen en un determinado momento en pantalla. Lo hacíamos así porque era lo más sencillo (cero procesamiento) y porque tiene la ventaja de ser lo más fieles posible a la fuente original. Pero tiene sentido cambiar y empezar a trabajar a nivel de frase:

* Es más intuitivo para el usuario ver frases como resultado de búsquedas que un fragmento de texto, tal vez sin sentido. (Aunque la idea era, en cualquier caso, mostrar fragmentos anteriores/posteriores.)

* Alejarnos un poco del formato VTT nos permite usar otras fuentes de entrada, como puede ser una transcripción hecha por Amazon Transcribe, o subtítulos a nivel de palabra.

* Al alejarnos de la especifidad de subtítulos, lo aprendido nos puede valer para análisis en textos escritos, no solo transcripciones.

* El análisis semántico se hace tradicionalmente sobre frases, sería muy raro hacerlo en fragmentos VTT. De cara a la segmentación por bloques (#7), también parece tenir sentido segmentar antes por frases.

Afortunadamente, el impacto sobre el prototipo existente es minimo, por no decir ninguno: cada unidad seguirá teniendo un tiempo de inicio y otro de fin, y poco más.

**Comment by jgsogo** [comment]
Hola! ¿Este _programilla_ lo tenéis por ahí a mano? Si en este repositorio está fundamentalmente la web, ¿tenéis en algún otro lado todos los scripts y las pruebas que vais haciendo?

Gracias por el currazo que os estáis metiendo con esto.

**Comment by dcabo** [comment]
@jgsogo ahora está en un repo aparte y es un poco caos, así que me asigne #95 para mover las partes relevantes aquí. Yo creo que entre mañana y el finde lo hago y lo tienes la semana que viene.
