### ISSUE TITLE
Error while processing subtitles file with the extract entities script

### ISSUE THREAD

**Issue by esebastian** [civio/verba#46]
The GitHub Actions workflow we configured in #22 started to fail three days ago, in the 'Extract entities' step.

The problem is that the extract entities script process gets killed while working in one specific subtitles file: `5473899.vtt`.

It looks like a memory exhaustion problem, because in a local environment with 16GB of RAM the process finishes correctly; and in `midas`, when the Elasticsearch and Kibana services are stopped, the process keeps working some more time before it ultimately still gets killed.

**Comment by dcabo** [comment]
Esto no ha vuelto a pasar, así que lo vamos a tratar como algo excepcional y de momento lo cierro.
