### ISSUE TITLE
Integrate short vignettes

### ISSUE THREAD

**Issue by dcabo** [civio/verba#58]

**Comment by carmen-tm** [comment]
He arreglado la query y los números de la viñeta ["El rigor científico, a dieta"](https://verba.civio.es/vignettes#vignette03l) por el tema del **plural** que comentamos ayer. 
La query es ahora  `"dieta" | "dietas"`. El cambio en número de resultados es significativo (más del 30% de apariciones). 

Al resto de viñetas no les afecta esto del plural al ser nombres propios, etc.
