### ISSUE TITLE
Añadir enlace al repositorio desde la web

### ISSUE THREAD

**Issue by dcabo** [civio/verba#89]
Bien desde el "Sobre nosotros" ¿o tal vez en el pie?

**Comment by EvaBelmonte** [comment]
En el Sobre nosotros tiene más sentido, creo

**Comment by carmen-tm** [comment]
He añadido el link en la sección Sobre Verba, cuando dice "Verba es además una aplicación web de [código abierto](https://github.com/civio/verba/)"
