### ISSUE TITLE
El nombre del programa en los resultados debería ser un enlace

### ISSUE THREAD

**Issue by dcabo** [civio/verba#94]
En la lista de resultados, el nombre del programa ("19/03/2019 | TD 15h") debería ser un enlace que lleve a la página con la transcripción completa. Igual con esto no hace falta #90, incluso.

**Comment by carmen-tm** [comment]
Hecho. De momento dejo también el #90 porque me parece que intuitivamente funciona bien, una vez dentro del fragmento del contexto.
